In [7]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [4]:
a = np.random.random((1,4))
print(a)
preprocessing.normalize(a)

[[0.36732744 0.46155437 0.89598432 0.91178343]]


array([[0.26091   , 0.3278387 , 0.63641112, 0.64763311]])

In [5]:
a = a*20
preprocessing.normalize(a)

array([[0.26091   , 0.3278387 , 0.63641112, 0.64763311]])

In [6]:
a = (np.random.random((4,4)))*50
print(a)

[[39.26049417  2.68901514 26.63888442 22.9023694 ]
 [34.02919288 18.02002394  1.03716002 10.24232815]
 [38.52557084 23.78419956  4.40110662 42.66379038]
 [ 7.03264621 35.63323474 20.15080641 32.99671207]]


In [12]:
df = pd.DataFrame(a,columns = ['Col1','Col2','Col3','Col4'])
df

Col1       Col2       Col3       Col4
0  39.260494   2.689015  26.638884  22.902369
1  34.029193  18.020024   1.037160  10.242328
2  38.525571  23.784200   4.401107  42.663790
3   7.032646  35.633235  20.150806  32.996712

In [23]:
df_max_scaled = df.copy()

for column in df_max_scaled.columns:
    df_max_scaled[column] = df_max_scaled[column]  / df_max_scaled[column].abs().max()
      
display(df_max_scaled)

Col1      Col2      Col3      Col4
0  0.421023 -1.000000  1.000000 -0.253490
1  0.190359 -0.115991 -0.884989 -1.000000
2  0.388618  0.216379 -0.637310  0.911759
3 -1.000000  0.899612  0.522300  0.341731

In [24]:
df_min_max_scaled = df.copy()
  

for column in df_min_max_scaled.columns:
    df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())    
  
display(df_min_max_scaled)

Col1      Col2      Col3      Col4
0  1.000000  0.000000  1.000000  0.390483
1  0.837678  0.465363  0.000000  0.000000
2  0.977196  0.640330  0.131395  1.000000
3  0.000000  1.000000  0.746577  0.701831

In [25]:
df_z_scaled = df.copy()
  
for column in df_z_scaled.columns:
    df_z_scaled[column] = (df_z_scaled[column] - df_z_scaled[column].mean()) / df_z_scaled[column].std()    
  
display(df_z_scaled)

Col1      Col2      Col3      Col4
0  0.624276 -1.266745  1.103829 -0.309507
1  0.282257 -0.146932 -0.976877 -1.220983
2  0.576227  0.274097 -0.703482  1.113242
3 -1.482759  1.139579  0.576529  0.417248